; Values are not used anywhere, this is just a list of reserved URL keywords
[Keywords]
dashboard=
controls=
master=
logout=

; Format:
; URL path=Controller class name?argument1,argument2,...
[Routes]
/=Index
/dashboard=Dashboard
/controls/master=MasterConfig
/tasks=Tasks
/logout=Logout
