; Values are not used anywhere, this is just a list of reserved URL keywords
[Keywords]
tasks=

; Format:
; URL path=Controller class name?argument1,argument2,...
[Routes]
/=Index
/tasks=Tasks
/login=Login
