; Values are not used anywhere, this is just a list of reserved URL keywords
[Keywords]
dashboard=
controls=
master=
tasks=
config=
log=
new=
logout=

; Format:
; URL path=Controller class name?argument1,argument2,...
[Routes]
/=Index
/dashboard=Dashboard
/controls/master=MasterConfig
/controls/tasks=Tasks
/controls/tasks/<0>/config=TaskConfig
/controls/tasks/<0>/log=TaskLog
/controls/tasks/new=NewTask
/logout=Logout
