<p>Vítejte ve správě hlavního robotického účtu WikiSkript, robota Sunnyho.</p>
<p>Pro přístup k ovládacímu panelu použijte odkaz v hlavičce stránky.</p>
<p>Vezměte prosím na vědomí, že pro většinu činností musíte být přihlášení a mít dostatečná oprávnění.</p>
<hr>
<p>
    Něco nefunguje? Kontaktujte webmastera skrze
    <a href="https://www.wikiskripta.eu/w/Diskuse_s_u%C5%BEivatelem:ShadyMedic">jeho diskusní stránku</a>
    nebo <a href="https://www.wikiskripta.eu/w/Speci%C3%A1ln%C3%AD:E-mail/ShadyMedic">e-mail</a>.
</p>

