<!DOCTYPE html>
<html lang="cs-CZ">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <?php foreach (self::$cssFiles as $cssFile) : ?>
        <link rel="stylesheet" href="/public/css/<?= $cssFile ?>.css">
    <?php endforeach ?>
    <script
            src="https://code.jquery.com/jquery-3.7.1.min.js"
            integrity="sha256-/JqT3SQfawRcv/BIHPThkBvs0OEvtFFmqPF/lYI/Cxo="
            crossorigin="anonymous"></script>
    <?php foreach (self::$jsFiles as $jsFile) : ?>
        <script type="text/javascript" src="/public/js/<?= $jsFile ?>.js"></script>
    <?php endforeach ?>
    <title>Správa robotů WikiSkript</title>
</head>
<body data-page-id="<?=
/** @var string $layout_page_id ID of the generated webpage, initialized in the specific controller */
$layout_page_id
?>">
<nav>
    <span class="nav-row">
        <a href="/" class="nav-item" style="background-color: #4076ff">Homepage</a>
        <a href="/dashboard" class="nav-item"  style="background-color: #7cff40">Ovládací panely</a>
    </span>
    <span class="nav-row">
        <a href="https://www.wikiskripta.eu" class="nav-item" style="background-color: #FFBE00">WikiSkripta</a>
        <a href="<?= is_null($layout_username) ? 'https://www.wikiskripta.eu/index.php?title=Speci%C3%A1ln%C3%AD:P%C5%99ihl%C3%A1sit&returnto=WikiSkripta:WikiBots_Redirect' : '/logout' ?>" class="nav-item" style="background-color: #ff4040">
            <?= is_null($layout_username) ? 'Přihlásit se' : 'Odhlásit se' ?>
        </a>
    </span>
</nav>
<?php if (!is_null($layout_username)) : ?>
<div id="user-info-bar">
    <span>Aktuálně přihlášen: <b><?= $layout_username ?></b>, skupiny: <?= implode(', ', $layout_usergroups) ?></span>
</div>
<?php endif ?>
<main>
    <header>
        <h1><?= $layout_title ?></h1>
    </header>
    <article>
        <?php require self::VIEWS_DIRECTORY.'/'.array_shift(self::$views).'.phtml'; ?>
    </article>
</main>
<footer>
    <div>Naprogramoval Jan Štěch.</div>
</footer>
</body>
</html>

