<p>Zde je seznam všech aktuálně dostupných procedur.</p>
<p>Po rozkliknutí detailů některé z nich můžete proceduru spustit.</p>
<table class="wide-table striped-table">
    <tr>
        <th>Název procedury</th>
        <th>Skupiny oprávněné<br>měnit konfiguraci</th>
        <th>Skupiny oprávněné<br>spouštět proceduru</th>
        <th>Skupiny oprávněné<br>prohlížet logy</th>
        <th>Akce</th>
    </tr>
    <?php foreach ($procedures_procedures as $procedure) : ?>
        <tr>
            <td><?= $procedure->getName() ?></td>
            <td>
                <?php foreach ($procedure->getAllowedConfigGroups() as $usergroup) : ?>
                    <?= \Wikibots\Models\UserGroupHelper::getGroupIcon($usergroup); ?>
                <?php endforeach ?>
            </td>
            <td>
                <?php foreach ($procedure->getAllowedRunGroups() as $usergroup) : ?>
                    <?= \Wikibots\Models\UserGroupHelper::getGroupIcon($usergroup); ?>
                <?php endforeach ?>
            </td>
            <td>
                <?php foreach ($procedure->getAllowedLogGroups() as $usergroup) : ?>
                    <?= \Wikibots\Models\UserGroupHelper::getGroupIcon($usergroup); ?>
                <?php endforeach ?>
            </td>
            <td>
                <a href="/controls/procedures/<?= $procedure->getUrl() ?>/config">Konfigurovat</a>
                <a href="/controls/procedures/<?= $procedure->getUrl() ?>/run">Spustit</a>
                <a href="/controls/procedures/<?= $procedure->getUrl() ?>/log">Prohlížet log</a>
            </td>
        </tr>
    <?php endforeach ?>
</table>
<p class="txt-c"><a href="/controls/procedures/new">Zaregistrovat novou proceduru</a></p>