<p>
    Dokumentace k této proceduře je dostupná na WikiSkriptech:
    <a href="<?= \Wikibots\Models\Settings::WS_DOCUMENTATION_BASE_URL.$procedurerun_documentation ?>" target="_blank">zde</a>.
</p>
<form method="post">
    <table>
        <?php foreach ($procedurerun_formcontrols as $formControl) : ?>
            <?= $formControl->render(); ?>
        <?php endforeach ?>
    </table>
    <input type="reset" value="Resetovat"/>
    <input type="submit" value="Spustit"/>
    <p>Procedura může běžet i několik minut (nebo i déle). Pokud chcete výstup obdržet přímo, zůstaňte po kliknutí na "Spustit" na této stránce. V opačném případě naleznete výstup po ukončení běhu v logu procedury.</p>
</form>
