<p>
    Dokumentace k této proceduře je dostupná na WikiSkriptech:
    <a href="<?= $_ENV['WIKI_PAGE_BASE_URL'].$procedurerun_documentation ?>" target="_blank">zde</a>.
</p>
<p <?= ($procedurerun_interval > $procedurerun_sincelastrun) ? 'class="error"' : '' ?>>
    Tato procedura může být spuštěna každých <strong><?= $procedurerun_interval ?> minut</strong>.<br>
    Naposledy byla spuštěna před <strong><?= $procedurerun_sincelastrun ?> minutami</strong>.
</p>
<form method="post" style="border: 1px solid black;">
    <table style="border-bottom: 1px dashed black;">
        <?php foreach ($procedurerun_formcontrols as $formControl) : ?>
            <?= $formControl->render(); ?>
        <?php endforeach ?>
        <tr>
            <td style="border-top: 1px dashed black;"><label for="comment">Důvod/komentář ke spuštění procedury (loguje se)</label></td>
            <td style="border-top: 1px dashed black;"><input id="comment" name="comment" type="text" required></td>
        </tr>
    </table>
    <input type="reset" value="Resetovat"/>
    <input type="submit" value="Spustit"/>
</form>
<p>Procedura může běžet i několik minut (nebo i déle). Pokud chcete výstup obdržet přímo, zůstaňte po kliknutí na "Spustit" na této stránce. V opačném případě naleznete výstup po ukončení běhu v <a href="log">logu procedury</a>.</p>
<pre class="procedure-output"><?= $procedurerun_output ?? '<i>Zde se zobrazí výstup.</i>' ?></pre>

